/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TailorsIndexRouteImport } from './routes/tailors/index'
import { Route as OrdersIndexRouteImport } from './routes/orders/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as TailorsIdRouteImport } from './routes/tailors/$id'
import { Route as OrdersIdRouteImport } from './routes/orders/$id'
import { Route as DashboardTailorRouteImport } from './routes/dashboard/tailor'
import { Route as DashboardAssistantRouteImport } from './routes/dashboard/assistant'
import { Route as DashboardAdminRouteImport } from './routes/dashboard/admin'
import { Route as AppTailorSettingsRouteImport } from './routes/app/tailor/settings'
import { Route as AppTailorReviewsRouteImport } from './routes/app/tailor/reviews'
import { Route as AppTailorProfileRouteImport } from './routes/app/tailor/profile'
import { Route as AppTailorEarningsRouteImport } from './routes/app/tailor/earnings'
import { Route as AppTailorDashboardRouteImport } from './routes/app/tailor/dashboard'
import { Route as AppTailorAppointmentsRouteImport } from './routes/app/tailor/appointments'
import { Route as AppAdminVerificationRouteImport } from './routes/app/admin/verification'
import { Route as AppAdminUsersRouteImport } from './routes/app/admin/users'
import { Route as AppAdminSettingsRouteImport } from './routes/app/admin/settings'
import { Route as AppAdminPaymentsRouteImport } from './routes/app/admin/payments'
import { Route as AppAdminOrdersRouteImport } from './routes/app/admin/orders'
import { Route as AppAdminDashboardRouteImport } from './routes/app/admin/dashboard'
import { Route as AppAdminComplaintsRouteImport } from './routes/app/admin/complaints'
import { Route as AppAdminAppointmentsRouteImport } from './routes/app/admin/appointments'
import { Route as AppAdminAnalyticsRouteImport } from './routes/app/admin/analytics'
import { Route as AppTailorOrdersIndexRouteImport } from './routes/app/tailor/orders/index'
import { Route as AppTailorCustomersIndexRouteImport } from './routes/app/tailor/customers/index'
import { Route as AppTailorOrdersIdRouteImport } from './routes/app/tailor/orders/$id'
import { Route as AppTailorCustomersIdRouteImport } from './routes/app/tailor/customers/$id'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorsIndexRoute = TailorsIndexRouteImport.update({
  id: '/tailors/',
  path: '/tailors/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorsIdRoute = TailorsIdRouteImport.update({
  id: '/tailors/$id',
  path: '/tailors/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTailorRoute = DashboardTailorRouteImport.update({
  id: '/dashboard/tailor',
  path: '/dashboard/tailor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAssistantRoute = DashboardAssistantRouteImport.update({
  id: '/dashboard/assistant',
  path: '/dashboard/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorSettingsRoute = AppTailorSettingsRouteImport.update({
  id: '/app/tailor/settings',
  path: '/app/tailor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorReviewsRoute = AppTailorReviewsRouteImport.update({
  id: '/app/tailor/reviews',
  path: '/app/tailor/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorProfileRoute = AppTailorProfileRouteImport.update({
  id: '/app/tailor/profile',
  path: '/app/tailor/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorEarningsRoute = AppTailorEarningsRouteImport.update({
  id: '/app/tailor/earnings',
  path: '/app/tailor/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorDashboardRoute = AppTailorDashboardRouteImport.update({
  id: '/app/tailor/dashboard',
  path: '/app/tailor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorAppointmentsRoute = AppTailorAppointmentsRouteImport.update({
  id: '/app/tailor/appointments',
  path: '/app/tailor/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminVerificationRoute = AppAdminVerificationRouteImport.update({
  id: '/app/admin/verification',
  path: '/app/admin/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/app/admin/users',
  path: '/app/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminSettingsRoute = AppAdminSettingsRouteImport.update({
  id: '/app/admin/settings',
  path: '/app/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminPaymentsRoute = AppAdminPaymentsRouteImport.update({
  id: '/app/admin/payments',
  path: '/app/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminOrdersRoute = AppAdminOrdersRouteImport.update({
  id: '/app/admin/orders',
  path: '/app/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminDashboardRoute = AppAdminDashboardRouteImport.update({
  id: '/app/admin/dashboard',
  path: '/app/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminComplaintsRoute = AppAdminComplaintsRouteImport.update({
  id: '/app/admin/complaints',
  path: '/app/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAppointmentsRoute = AppAdminAppointmentsRouteImport.update({
  id: '/app/admin/appointments',
  path: '/app/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/app/admin/analytics',
  path: '/app/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorOrdersIndexRoute = AppTailorOrdersIndexRouteImport.update({
  id: '/app/tailor/orders/',
  path: '/app/tailor/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorCustomersIndexRoute = AppTailorCustomersIndexRouteImport.update({
  id: '/app/tailor/customers/',
  path: '/app/tailor/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorOrdersIdRoute = AppTailorOrdersIdRouteImport.update({
  id: '/app/tailor/orders/$id',
  path: '/app/tailor/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTailorCustomersIdRoute = AppTailorCustomersIdRouteImport.update({
  id: '/app/tailor/customers/$id',
  path: '/app/tailor/customers/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/designer': typeof DesignerRoute
  '/profile': typeof ProfileRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/tailor': typeof DashboardTailorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/tailors/$id': typeof TailorsIdRoute
  '/app/': typeof AppIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/tailors/': typeof TailorsIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/appointments': typeof AppAdminAppointmentsRoute
  '/app/admin/complaints': typeof AppAdminComplaintsRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/tailor/appointments': typeof AppTailorAppointmentsRoute
  '/app/tailor/dashboard': typeof AppTailorDashboardRoute
  '/app/tailor/earnings': typeof AppTailorEarningsRoute
  '/app/tailor/profile': typeof AppTailorProfileRoute
  '/app/tailor/reviews': typeof AppTailorReviewsRoute
  '/app/tailor/settings': typeof AppTailorSettingsRoute
  '/app/tailor/customers/$id': typeof AppTailorCustomersIdRoute
  '/app/tailor/orders/$id': typeof AppTailorOrdersIdRoute
  '/app/tailor/customers/': typeof AppTailorCustomersIndexRoute
  '/app/tailor/orders/': typeof AppTailorOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/designer': typeof DesignerRoute
  '/profile': typeof ProfileRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/tailor': typeof DashboardTailorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/tailors/$id': typeof TailorsIdRoute
  '/app': typeof AppIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/tailors': typeof TailorsIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/appointments': typeof AppAdminAppointmentsRoute
  '/app/admin/complaints': typeof AppAdminComplaintsRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/tailor/appointments': typeof AppTailorAppointmentsRoute
  '/app/tailor/dashboard': typeof AppTailorDashboardRoute
  '/app/tailor/earnings': typeof AppTailorEarningsRoute
  '/app/tailor/profile': typeof AppTailorProfileRoute
  '/app/tailor/reviews': typeof AppTailorReviewsRoute
  '/app/tailor/settings': typeof AppTailorSettingsRoute
  '/app/tailor/customers/$id': typeof AppTailorCustomersIdRoute
  '/app/tailor/orders/$id': typeof AppTailorOrdersIdRoute
  '/app/tailor/customers': typeof AppTailorCustomersIndexRoute
  '/app/tailor/orders': typeof AppTailorOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/designer': typeof DesignerRoute
  '/profile': typeof ProfileRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/assistant': typeof DashboardAssistantRoute
  '/dashboard/tailor': typeof DashboardTailorRoute
  '/orders/$id': typeof OrdersIdRoute
  '/tailors/$id': typeof TailorsIdRoute
  '/app/': typeof AppIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/tailors/': typeof TailorsIndexRoute
  '/app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/app/admin/appointments': typeof AppAdminAppointmentsRoute
  '/app/admin/complaints': typeof AppAdminComplaintsRoute
  '/app/admin/dashboard': typeof AppAdminDashboardRoute
  '/app/admin/orders': typeof AppAdminOrdersRoute
  '/app/admin/payments': typeof AppAdminPaymentsRoute
  '/app/admin/settings': typeof AppAdminSettingsRoute
  '/app/admin/users': typeof AppAdminUsersRoute
  '/app/admin/verification': typeof AppAdminVerificationRoute
  '/app/tailor/appointments': typeof AppTailorAppointmentsRoute
  '/app/tailor/dashboard': typeof AppTailorDashboardRoute
  '/app/tailor/earnings': typeof AppTailorEarningsRoute
  '/app/tailor/profile': typeof AppTailorProfileRoute
  '/app/tailor/reviews': typeof AppTailorReviewsRoute
  '/app/tailor/settings': typeof AppTailorSettingsRoute
  '/app/tailor/customers/$id': typeof AppTailorCustomersIdRoute
  '/app/tailor/orders/$id': typeof AppTailorOrdersIdRoute
  '/app/tailor/customers/': typeof AppTailorCustomersIndexRoute
  '/app/tailor/orders/': typeof AppTailorOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/book'
    | '/designer'
    | '/profile'
    | '/dashboard/admin'
    | '/dashboard/assistant'
    | '/dashboard/tailor'
    | '/orders/$id'
    | '/tailors/$id'
    | '/app/'
    | '/orders/'
    | '/tailors/'
    | '/app/admin/analytics'
    | '/app/admin/appointments'
    | '/app/admin/complaints'
    | '/app/admin/dashboard'
    | '/app/admin/orders'
    | '/app/admin/payments'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/admin/verification'
    | '/app/tailor/appointments'
    | '/app/tailor/dashboard'
    | '/app/tailor/earnings'
    | '/app/tailor/profile'
    | '/app/tailor/reviews'
    | '/app/tailor/settings'
    | '/app/tailor/customers/$id'
    | '/app/tailor/orders/$id'
    | '/app/tailor/customers/'
    | '/app/tailor/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/book'
    | '/designer'
    | '/profile'
    | '/dashboard/admin'
    | '/dashboard/assistant'
    | '/dashboard/tailor'
    | '/orders/$id'
    | '/tailors/$id'
    | '/app'
    | '/orders'
    | '/tailors'
    | '/app/admin/analytics'
    | '/app/admin/appointments'
    | '/app/admin/complaints'
    | '/app/admin/dashboard'
    | '/app/admin/orders'
    | '/app/admin/payments'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/admin/verification'
    | '/app/tailor/appointments'
    | '/app/tailor/dashboard'
    | '/app/tailor/earnings'
    | '/app/tailor/profile'
    | '/app/tailor/reviews'
    | '/app/tailor/settings'
    | '/app/tailor/customers/$id'
    | '/app/tailor/orders/$id'
    | '/app/tailor/customers'
    | '/app/tailor/orders'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/book'
    | '/designer'
    | '/profile'
    | '/dashboard/admin'
    | '/dashboard/assistant'
    | '/dashboard/tailor'
    | '/orders/$id'
    | '/tailors/$id'
    | '/app/'
    | '/orders/'
    | '/tailors/'
    | '/app/admin/analytics'
    | '/app/admin/appointments'
    | '/app/admin/complaints'
    | '/app/admin/dashboard'
    | '/app/admin/orders'
    | '/app/admin/payments'
    | '/app/admin/settings'
    | '/app/admin/users'
    | '/app/admin/verification'
    | '/app/tailor/appointments'
    | '/app/tailor/dashboard'
    | '/app/tailor/earnings'
    | '/app/tailor/profile'
    | '/app/tailor/reviews'
    | '/app/tailor/settings'
    | '/app/tailor/customers/$id'
    | '/app/tailor/orders/$id'
    | '/app/tailor/customers/'
    | '/app/tailor/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  DesignerRoute: typeof DesignerRoute
  ProfileRoute: typeof ProfileRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardAssistantRoute: typeof DashboardAssistantRoute
  DashboardTailorRoute: typeof DashboardTailorRoute
  OrdersIdRoute: typeof OrdersIdRoute
  TailorsIdRoute: typeof TailorsIdRoute
  AppIndexRoute: typeof AppIndexRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  TailorsIndexRoute: typeof TailorsIndexRoute
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminAppointmentsRoute: typeof AppAdminAppointmentsRoute
  AppAdminComplaintsRoute: typeof AppAdminComplaintsRoute
  AppAdminDashboardRoute: typeof AppAdminDashboardRoute
  AppAdminOrdersRoute: typeof AppAdminOrdersRoute
  AppAdminPaymentsRoute: typeof AppAdminPaymentsRoute
  AppAdminSettingsRoute: typeof AppAdminSettingsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
  AppAdminVerificationRoute: typeof AppAdminVerificationRoute
  AppTailorAppointmentsRoute: typeof AppTailorAppointmentsRoute
  AppTailorDashboardRoute: typeof AppTailorDashboardRoute
  AppTailorEarningsRoute: typeof AppTailorEarningsRoute
  AppTailorProfileRoute: typeof AppTailorProfileRoute
  AppTailorReviewsRoute: typeof AppTailorReviewsRoute
  AppTailorSettingsRoute: typeof AppTailorSettingsRoute
  AppTailorCustomersIdRoute: typeof AppTailorCustomersIdRoute
  AppTailorOrdersIdRoute: typeof AppTailorOrdersIdRoute
  AppTailorCustomersIndexRoute: typeof AppTailorCustomersIndexRoute
  AppTailorOrdersIndexRoute: typeof AppTailorOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailors/': {
      id: '/tailors/'
      path: '/tailors'
      fullPath: '/tailors/'
      preLoaderRoute: typeof TailorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailors/$id': {
      id: '/tailors/$id'
      path: '/tailors/$id'
      fullPath: '/tailors/$id'
      preLoaderRoute: typeof TailorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tailor': {
      id: '/dashboard/tailor'
      path: '/dashboard/tailor'
      fullPath: '/dashboard/tailor'
      preLoaderRoute: typeof DashboardTailorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/assistant': {
      id: '/dashboard/assistant'
      path: '/dashboard/assistant'
      fullPath: '/dashboard/assistant'
      preLoaderRoute: typeof DashboardAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/settings': {
      id: '/app/tailor/settings'
      path: '/app/tailor/settings'
      fullPath: '/app/tailor/settings'
      preLoaderRoute: typeof AppTailorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/reviews': {
      id: '/app/tailor/reviews'
      path: '/app/tailor/reviews'
      fullPath: '/app/tailor/reviews'
      preLoaderRoute: typeof AppTailorReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/profile': {
      id: '/app/tailor/profile'
      path: '/app/tailor/profile'
      fullPath: '/app/tailor/profile'
      preLoaderRoute: typeof AppTailorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/earnings': {
      id: '/app/tailor/earnings'
      path: '/app/tailor/earnings'
      fullPath: '/app/tailor/earnings'
      preLoaderRoute: typeof AppTailorEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/dashboard': {
      id: '/app/tailor/dashboard'
      path: '/app/tailor/dashboard'
      fullPath: '/app/tailor/dashboard'
      preLoaderRoute: typeof AppTailorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/appointments': {
      id: '/app/tailor/appointments'
      path: '/app/tailor/appointments'
      fullPath: '/app/tailor/appointments'
      preLoaderRoute: typeof AppTailorAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/verification': {
      id: '/app/admin/verification'
      path: '/app/admin/verification'
      fullPath: '/app/admin/verification'
      preLoaderRoute: typeof AppAdminVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/users': {
      id: '/app/admin/users'
      path: '/app/admin/users'
      fullPath: '/app/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/settings': {
      id: '/app/admin/settings'
      path: '/app/admin/settings'
      fullPath: '/app/admin/settings'
      preLoaderRoute: typeof AppAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/payments': {
      id: '/app/admin/payments'
      path: '/app/admin/payments'
      fullPath: '/app/admin/payments'
      preLoaderRoute: typeof AppAdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/orders': {
      id: '/app/admin/orders'
      path: '/app/admin/orders'
      fullPath: '/app/admin/orders'
      preLoaderRoute: typeof AppAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/dashboard': {
      id: '/app/admin/dashboard'
      path: '/app/admin/dashboard'
      fullPath: '/app/admin/dashboard'
      preLoaderRoute: typeof AppAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/complaints': {
      id: '/app/admin/complaints'
      path: '/app/admin/complaints'
      fullPath: '/app/admin/complaints'
      preLoaderRoute: typeof AppAdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/appointments': {
      id: '/app/admin/appointments'
      path: '/app/admin/appointments'
      fullPath: '/app/admin/appointments'
      preLoaderRoute: typeof AppAdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/admin/analytics': {
      id: '/app/admin/analytics'
      path: '/app/admin/analytics'
      fullPath: '/app/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/orders/': {
      id: '/app/tailor/orders/'
      path: '/app/tailor/orders'
      fullPath: '/app/tailor/orders/'
      preLoaderRoute: typeof AppTailorOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/customers/': {
      id: '/app/tailor/customers/'
      path: '/app/tailor/customers'
      fullPath: '/app/tailor/customers/'
      preLoaderRoute: typeof AppTailorCustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/orders/$id': {
      id: '/app/tailor/orders/$id'
      path: '/app/tailor/orders/$id'
      fullPath: '/app/tailor/orders/$id'
      preLoaderRoute: typeof AppTailorOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/tailor/customers/$id': {
      id: '/app/tailor/customers/$id'
      path: '/app/tailor/customers/$id'
      fullPath: '/app/tailor/customers/$id'
      preLoaderRoute: typeof AppTailorCustomersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  DesignerRoute: DesignerRoute,
  ProfileRoute: ProfileRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardAssistantRoute: DashboardAssistantRoute,
  DashboardTailorRoute: DashboardTailorRoute,
  OrdersIdRoute: OrdersIdRoute,
  TailorsIdRoute: TailorsIdRoute,
  AppIndexRoute: AppIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  TailorsIndexRoute: TailorsIndexRoute,
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminAppointmentsRoute: AppAdminAppointmentsRoute,
  AppAdminComplaintsRoute: AppAdminComplaintsRoute,
  AppAdminDashboardRoute: AppAdminDashboardRoute,
  AppAdminOrdersRoute: AppAdminOrdersRoute,
  AppAdminPaymentsRoute: AppAdminPaymentsRoute,
  AppAdminSettingsRoute: AppAdminSettingsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
  AppAdminVerificationRoute: AppAdminVerificationRoute,
  AppTailorAppointmentsRoute: AppTailorAppointmentsRoute,
  AppTailorDashboardRoute: AppTailorDashboardRoute,
  AppTailorEarningsRoute: AppTailorEarningsRoute,
  AppTailorProfileRoute: AppTailorProfileRoute,
  AppTailorReviewsRoute: AppTailorReviewsRoute,
  AppTailorSettingsRoute: AppTailorSettingsRoute,
  AppTailorCustomersIdRoute: AppTailorCustomersIdRoute,
  AppTailorOrdersIdRoute: AppTailorOrdersIdRoute,
  AppTailorCustomersIndexRoute: AppTailorCustomersIndexRoute,
  AppTailorOrdersIndexRoute: AppTailorOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
